# Generated by Django 5.1.8 on 2025-06-03 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biz_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_name', models.CharField(max_length=255)),
                ('biz_description', models.TextField(blank=True, null=True)),
                ('biz_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('biz_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BizPriceListSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('has_gst', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('product_name', models.CharField(max_length=255)),
                ('business_plan_id', models.IntegerField()),
                ('business_plan_name', models.CharField(max_length=255)),
                ('original_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emudhra_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emudhra_name', models.CharField(max_length=255)),
                ('emudhra_description', models.TextField(blank=True, null=True)),
                ('emudhra_image', models.ImageField(upload_to='products/')),
                ('emudhra_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmudhraPriceListSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('has_gst', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('product_name', models.CharField(max_length=255)),
                ('product_type_detail', models.CharField(max_length=255)),
                ('basic_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fusiontec_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fusiontec_name', models.CharField(max_length=255)),
                ('fusiontec_description', models.TextField(blank=True, null=True)),
                ('fusiontec_image', models.ImageField(upload_to='products/')),
                ('fusiontec_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FusiontecPriceListSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('has_gst', models.CharField(max_length=10)),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('product_name', models.CharField(max_length=100)),
                ('product_type_detail', models.CharField(max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tally_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tally_name', models.CharField(max_length=255)),
                ('tally_description', models.TextField(blank=True, null=True)),
                ('tally_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('tally_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TallyPriceListSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('has_gst', models.BooleanField(default=True)),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('product_name', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=50)),
                ('product_type_detail', models.CharField(blank=True, max_length=100, null=True)),
                ('basic_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='biz_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('billing_cycle', models.CharField(blank=True, default='Billed for 1 Year | Per Device', max_length=255, null=True)),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('team_name', models.CharField(default='For Sales Team', max_length=255)),
                ('biz_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.biz_4')),
            ],
        ),
        migrations.CreateModel(
            name='Emudhra_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_product', models.CharField(max_length=255, null=True)),
                ('emudhra_rate', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('emudhra_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.emudhra_2')),
            ],
        ),
        migrations.CreateModel(
            name='Fusiontec_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fusiontec_product', models.CharField(max_length=255, null=True)),
                ('fusiontec_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.fusiontec_3')),
            ],
        ),
        migrations.CreateModel(
            name='Tally_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('basic_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('tally_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.tally_1')),
            ],
        ),
        migrations.CreateModel(
            name='Tally_Software_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('basic_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('tally_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='products.tally_1')),
            ],
        ),
        migrations.CreateModel(
            name='Tally_Upgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('basic_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('tally_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrades', to='products.tally_1')),
            ],
        ),
    ]
