# Generated by Django 5.2.4 on 2025-12-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(help_text='Promotional image for new products', upload_to='products/new_products/')),
                ('title', models.CharField(blank=True, help_text='Optional title for the product', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description for the product', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this product should be displayed')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for display (lower numbers appear first)')),
            ],
            options={
                'verbose_name': 'New Product',
                'verbose_name_plural': 'New Products',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
