# Generated by Django 5.2.4 on 2025-08-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DscSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("mobile", models.CharField(max_length=20)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("gst_number", models.CharField(blank=True, max_length=20, null=True)),
                ("class_type", models.CharField(max_length=20)),
                ("user_type", models.CharField(max_length=20)),
                ("cert_type", models.CharField(max_length=20)),
                ("validity", models.CharField(max_length=5)),
                ("include_token", models.BooleanField(default=False)),
                ("include_installation", models.BooleanField(default=False)),
                ("outside_india", models.BooleanField(default=False)),
                (
                    "quoted_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "razorpay_order_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("payment_received", "Payment Received"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "DSC Submission",
                "verbose_name_plural": "DSC Submissions",
                "ordering": ["-created_at"],
            },
        ),
    ]
