# Generated by Django 5.1.8 on 2025-06-17 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tallypricelistsubmission',
            old_name='area',
            new_name='district',
        ),
    ]
