# Generated by Django 5.1.8 on 2025-05-29 10:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_pricelistsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelistsubmission',
            name='has_gst',
        ),
        migrations.AddField(
            model_name='pricelistsubmission',
            name='gst_status',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricelistsubmission',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pricelistsubmission',
            name='product_name',
            field=models.CharField(choices=[('Tally', 'Tally'), ('E-Mudhra', 'E-Mudhra'), ('Pantasign', 'Pantasign'), ('Biz Analyst', 'Biz Analyst')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pricelistsubmission',
            name='product_type',
            field=models.CharField(max_length=50),
        ),
    ]
