# Generated by Django 5.1.8 on 2025-05-29 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_pricelistsubmission_has_gst_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceListSubmission',
        ),
    ]
