# Generated by Django 5.1.8 on 2025-06-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_razorpaytransactionform'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpaytransactionform',
            name='product_detail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='razorpaytransactionform',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='razorpaytransactionform',
            name='product_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
