# Generated by Django 5.1.8 on 2025-05-29 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_pricelistsubmission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceListSubmission',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
