# Generated by Django 5.1.8 on 2025-06-18 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_razorpaytransactionform_product_detail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='razorpaytransactionform',
            old_name='product_type',
            new_name='product_type_detail',
        ),
    ]
