# Generated by Django 5.1.8 on 2025-05-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
