# Generated by Django 5.1.8 on 2025-06-18 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_product_type_razorpaytransactionform_product_type_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='razorpaytransactionform',
            name='product_detail',
        ),
    ]
