# Generated by Django 5.1.8 on 2025-06-18 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_razorpaytransactionform_product_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='razorpaytransactionform',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='razorpaytransactionform',
            name='product_type_detail',
        ),
    ]
