# Generated by Django 5.1.8 on 2025-06-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_razorpaytransactionform_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpaytransactionform',
            name='product_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
