# Generated by Django 5.1.8 on 2025-06-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_razorpaytransactionform_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPaymentInfoQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='FUSIONTEC SOFTWARE', max_length=100)),
                ('upi_id', models.CharField(max_length=100)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
            ],
        ),
        migrations.DeleteModel(
            name='RazorpayTransaction',
        ),
    ]
