# Generated by Django 5.1.8 on 2025-05-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_producttypea_producttypeb_producttypec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttypea',
            name='name',
        ),
        migrations.RemoveField(
            model_name='producttypeb',
            name='name',
        ),
        migrations.RemoveField(
            model_name='producttypec',
            name='name',
        ),
        migrations.AddField(
            model_name='producttypea',
            name='basic_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producttypea',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=0, help_text='CGST @ 9%', max_digits=10),
        ),
        migrations.AddField(
            model_name='producttypea',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=0, help_text='SGST @ 9%', max_digits=10),
        ),
        migrations.AddField(
            model_name='producttypea',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='producttypea',
            name='type_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producttypeb',
            name='basic_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producttypeb',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=0, help_text='CGST @ 9%', max_digits=10),
        ),
        migrations.AddField(
            model_name='producttypeb',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=0, help_text='SGST @ 9%', max_digits=10),
        ),
        migrations.AddField(
            model_name='producttypeb',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='producttypeb',
            name='type_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producttypec',
            name='basic_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producttypec',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=0, help_text='CGST @ 9%', max_digits=10),
        ),
        migrations.AddField(
            model_name='producttypec',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=0, help_text='SGST @ 9%', max_digits=10),
        ),
        migrations.AddField(
            model_name='producttypec',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='producttypec',
            name='type_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='basic_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='type_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
