# Generated by Django 5.1.8 on 2025-06-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_banktransferinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Online Payment (Razorpay)', max_length=100)),
                ('description', models.TextField(default='Secure payment via Razorpay.')),
                ('payment_button_id', models.CharField(help_text='Paste Razorpay payment_button_id here', max_length=100)),
            ],
        ),
    ]
