# Generated by Django 5.1.8 on 2025-05-30 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_producttypea_name_remove_producttypeb_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Product1',
        ),
        migrations.RenameField(
            model_name='producttype',
            old_name='product',
            new_name='Product1',
        ),
    ]
