# Generated by Django 5.1.8 on 2025-05-30 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_rename_product_product1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductTypeC',
        ),
    ]
