# Generated by Django 5.1.8 on 2025-06-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_emudhra_product_cgst_emudhra_product_sgst_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emudhra_product',
            old_name='emudhra_rate',
            new_name='basic_amount',
        ),
        migrations.AlterField(
            model_name='emudhra_product',
            name='cgst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='emudhra_product',
            name='sgst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='emudhra_product',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True),
        ),
    ]
