# Generated by Django 5.1.8 on 2025-05-30 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_delete_producttypec'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductType',
            new_name='Tally_Products',
        ),
    ]
