# Generated by Django 5.1.8 on 2025-05-30 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_rename_producttype_tally_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductTypeA',
            new_name='Tally_Software_Services',
        ),
    ]
