# Generated by Django 5.2.3 on 2025-06-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_biz_product_cgst_biz_product_sgst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bizpricelistsubmission',
            name='actual_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
