# Generated by Django 5.1.8 on 2025-05-30 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_rename_producttypea_tally_software_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductTypeB',
            new_name='Tally_Upgrades',
        ),
    ]
