# Generated by Django 5.2.3 on 2025-06-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_bizpricelistsubmission_actual_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bizpricelistsubmission',
            name='actual_price',
        ),
        migrations.AddField(
            model_name='bizpricelistsubmission',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
