# Generated by Django 5.1.8 on 2025-05-31 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_rename_producttypeb_tally_upgrades'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product1',
            new_name='Tally_1',
        ),
        migrations.RenameModel(
            old_name='Tally_Products',
            new_name='Tally_Product',
        ),
        migrations.RenameModel(
            old_name='Tally_Upgrades',
            new_name='Tally_Software_Service',
        ),
        migrations.RenameModel(
            old_name='Tally_Software_Services',
            new_name='Tally_Upgrade',
        ),
        migrations.RenameField(
            model_name='tally_product',
            old_name='Product1',
            new_name='Tally_1',
        ),
    ]
