# Generated by Django 5.1.8 on 2025-05-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_rename_product1_tally_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emudhra_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
