# Generated by Django 5.2.3 on 2025-06-20 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_bizpricelistsubmission_actual_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bizpricelistsubmission',
            name='new_price',
        ),
    ]
