# Generated by Django 5.2.3 on 2025-06-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_bizpricelistsubmission_new_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bizpricelistsubmission',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
