# Generated by Django 5.1.8 on 2025-05-31 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_emudhra_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tally_product',
            old_name='Tally_1',
            new_name='tally_1',
        ),
        migrations.RenameField(
            model_name='tally_software_service',
            old_name='product',
            new_name='tally_1',
        ),
        migrations.RenameField(
            model_name='tally_upgrade',
            old_name='product',
            new_name='tally_1',
        ),
        migrations.CreateModel(
            name='Emudhra_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_product', models.CharField(max_length=255, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('emudhra_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.emudhra_2')),
            ],
        ),
    ]
