# Generated by Django 5.1.8 on 2025-05-31 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_rename_tally_1_tally_product_tally_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fusiontec_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fusiontec_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fusiontec_product', models.CharField(max_length=255, null=True)),
                ('fusiontec_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.fusiontec_3')),
            ],
        ),
    ]
