# Generated by Django 5.0.14 on 2025-06-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0020_bizpricelistsubmission_new_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("pan_number", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "aadhar_number",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                (
                    "mobile_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("reference", models.CharField(max_length=255)),
                ("reference_contact", models.CharField(max_length=15)),
                (
                    "pan_copy",
                    models.FileField(blank=True, null=True, upload_to="uploads/pan/"),
                ),
                (
                    "aadhar_copy",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/aadhar/"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/photo/"
                    ),
                ),
                (
                    "gst_certificate",
                    models.FileField(blank=True, null=True, upload_to="uploads/gst/"),
                ),
                (
                    "authorization_letter",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/authorization/"
                    ),
                ),
                (
                    "company_pan",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/company_pan/"
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
