# Generated by Django 5.2.4 on 2025-07-31 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_applicant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biz_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(blank=True, max_length=255, null=True)),
                ('plan_description', models.TextField(blank=True, null=True)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('billing_cycle', models.CharField(blank=True, default='Billed for 1 Year | Per Device', max_length=255, null=True)),
                ('biz_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='products.biz_4')),
            ],
        ),
        migrations.CreateModel(
            name='Biz_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=255, null=True)),
                ('service_description', models.TextField(blank=True, null=True)),
                ('basic_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('billing_cycle', models.CharField(blank=True, default='Billed for 1 Year | Per Device', max_length=255, null=True)),
                ('biz_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='products.biz_4')),
            ],
        ),
        migrations.CreateModel(
            name='Fusiontec_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=255, null=True)),
                ('service_description', models.TextField(blank=True, null=True)),
                ('basic_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('fusiontec_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='products.fusiontec_3')),
            ],
        ),
        migrations.CreateModel(
            name='Fusiontec_Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(blank=True, max_length=255, null=True)),
                ('software_description', models.TextField(blank=True, null=True)),
                ('basic_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('fusiontec_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software', to='products.fusiontec_3')),
            ],
        ),
    ]
