# Generated by Django 5.1.8 on 2025-05-31 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_fusiontec_3_fusiontec_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emudhra_2',
            old_name='description',
            new_name='emudhra_description',
        ),
        migrations.RenameField(
            model_name='emudhra_2',
            old_name='image',
            new_name='emudhra_image',
        ),
        migrations.RenameField(
            model_name='emudhra_2',
            old_name='link',
            new_name='emudhra_link',
        ),
        migrations.RenameField(
            model_name='emudhra_2',
            old_name='name',
            new_name='emudhra_name',
        ),
        migrations.RenameField(
            model_name='emudhra_product',
            old_name='rate',
            new_name='emudhra_rate',
        ),
        migrations.RenameField(
            model_name='fusiontec_3',
            old_name='description',
            new_name='fusiontec_description',
        ),
        migrations.RenameField(
            model_name='fusiontec_3',
            old_name='image',
            new_name='fusiontec_image',
        ),
        migrations.RenameField(
            model_name='fusiontec_3',
            old_name='link',
            new_name='fusiontec_link',
        ),
        migrations.RenameField(
            model_name='fusiontec_3',
            old_name='name',
            new_name='fusiontec_name',
        ),
        migrations.RenameField(
            model_name='tally_1',
            old_name='description',
            new_name='tally_description',
        ),
        migrations.RenameField(
            model_name='tally_1',
            old_name='image',
            new_name='tally_image',
        ),
        migrations.RenameField(
            model_name='tally_1',
            old_name='link',
            new_name='tally_link',
        ),
        migrations.RenameField(
            model_name='tally_1',
            old_name='name',
            new_name='tally_name',
        ),
    ]
