# Generated by Django 5.1.8 on 2025-05-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_rename_description_emudhra_2_emudhra_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='biz_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_name', models.CharField(max_length=255)),
                ('biz_description', models.TextField(blank=True, null=True)),
                ('biz_image', models.ImageField(upload_to='products/')),
                ('biz_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
