# Generated by Django 5.1.8 on 2025-05-31 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_biz_4'),
    ]

    operations = [
        migrations.CreateModel(
            name='biz_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('billing_cycle', models.CharField(blank=True, default='Billed for 1 Year | Per Device', max_length=255, null=True)),
                ('biz_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.biz_4')),
            ],
        ),
    ]
