# Generated by Django 5.1.8 on 2025-05-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_biz_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biz_product',
            name='product_name',
        ),
        migrations.AddField(
            model_name='biz_product',
            name='team_name',
            field=models.CharField(default='For Sales Team', max_length=255),
        ),
    ]
