# Generated by Django 5.2.4 on 2025-08-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_biz_plan_installing_charges_biz_plan_token_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallypricelistsubmission',
            name='installing_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tallypricelistsubmission',
            name='token_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tallypricelistsubmission',
            name='token_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
