# Generated by Django 5.2.4 on 2025-08-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_tallypricelistsubmission_installing_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fusiontec_product',
            name='basic_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fusiontec_product',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fusiontec_product',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fusiontec_product',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
