# Generated by Django 5.2.4 on 2025-08-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_fusiontec_product_basic_amount_and_more'),
    ]

    operations = [
        # This is a merge migration to resolve dependency issues
    ]
