# Generated by Django 5.2.4 on 2025-08-09 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_customer_paymentsettings_paymenttransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateCardMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate_code', models.CharField(blank=True, help_text='Optional identifier for this rate card', max_length=50, null=True)),
                ('rate_date', models.DateField(help_text='Effective date for this rate')),
                ('base_amount', models.DecimalField(decimal_places=2, help_text='Base amount before GST', max_digits=10)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=18.0, help_text='GST percentage to apply (e.g., 18 for 18%)', max_digits=5)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Computed net amount including GST', max_digits=10)),
                ('product_item', models.ForeignKey(help_text='Product that this rate card applies to', on_delete=django.db.models.deletion.CASCADE, related_name='rate_cards', to='products.productitem')),
            ],
            options={
                'verbose_name': 'Rate Card',
                'verbose_name_plural': 'Rate Cards',
                'ordering': ['-rate_date', 'product_item__item_name'],
                'constraints': [models.UniqueConstraint(fields=('product_item', 'rate_date'), name='unique_rate_per_item_and_date')],
            },
        ),
    ]
