# Generated by Django 5.2.4 on 2025-08-09 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_ratecardmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prdt_desc', models.CharField(max_length=255, verbose_name='PrdtTDesc')),
            ],
            options={
                'verbose_name': 'Product Type Master',
                'verbose_name_plural': 'Product Type Master',
                'db_table': 'ProductTypeMaster',
            },
        ),
        migrations.CreateModel(
            name='ProductMasterV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prdt_desc', models.CharField(max_length=255, verbose_name='PrdtDesc')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.producttypemaster', verbose_name='PrdtTId')),
            ],
            options={
                'verbose_name': 'Product Master (Simple)',
                'verbose_name_plural': 'Product Master (Simple)',
                'db_table': 'ProductMaster',
            },
        ),
        migrations.CreateModel(
            name='RateCardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_date', models.DateField(verbose_name='RateCDate')),
                ('base_amt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='BaseAmt')),
                ('gst_percent', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='GST%')),
                ('nett_amt', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='NettAmt')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_cards', to='products.productmasterv2', verbose_name='PrdtId')),
            ],
            options={
                'verbose_name': 'Rate Card',
                'verbose_name_plural': 'Rate Cards',
                'db_table': 'RateCardMaster',
                'ordering': ['-rate_date', 'product__id'],
                'constraints': [models.UniqueConstraint(fields=('product', 'rate_date'), name='unique_rate_per_product_and_date')],
            },
        ),
    ]
