# Generated by Django 5.2.4 on 2025-08-09 09:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_producttypemaster_productmasterv2_ratecardentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttypemaster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttypemaster',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/types/', verbose_name='Type Image'),
        ),
        migrations.AddField(
            model_name='producttypemaster',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ratecardentry',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='CGST Amount'),
        ),
        migrations.AddField(
            model_name='ratecardentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratecardentry',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='SGST Amount'),
        ),
        migrations.AddField(
            model_name='ratecardentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
