# Generated by Django 5.2.4 on 2025-08-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_add_missing_timestamp_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratecardentry',
            name='installation_cgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Installation CGST'),
        ),
        migrations.AddField(
            model_name='ratecardentry',
            name='installation_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Installation Charge'),
        ),
        migrations.AddField(
            model_name='ratecardentry',
            name='installation_gst_percent',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='Installation GST%'),
        ),
        migrations.AddField(
            model_name='ratecardentry',
            name='installation_sgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Installation SGST'),
        ),
        migrations.AddField(
            model_name='ratecardentry',
            name='installation_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Installation Total'),
        ),
        migrations.AddField(
            model_name='ratecardentry',
            name='token_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Token Amount'),
        ),
        migrations.AddField(
            model_name='ratecardentry',
            name='token_cgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Token CGST'),
        ),
        migrations.AddField(
            model_name='ratecardentry',
            name='token_desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Token Description'),
        ),
        migrations.AddField(
            model_name='ratecardentry',
            name='token_gst_percent',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='Token GST%'),
        ),
        migrations.AddField(
            model_name='ratecardentry',
            name='token_sgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Token SGST'),
        ),
        migrations.AddField(
            model_name='ratecardentry',
            name='token_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Token Total'),
        ),
    ]
