# Generated by Django 5.2.4 on 2025-08-09 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_productmasterv2_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratecardentry',
            name='t_amount',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=10,
                verbose_name='Total Amount'
            ),
        ),
    ]
