# Generated by Django 5.2.4 on 2025-08-11 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20250809_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Name')),
                ('mobile', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email ID')),
                ('has_gst', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, verbose_name='Has GST')),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='GST Number')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='District')),
                ('pincode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Pincode')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('basic_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Basic Amount')),
                ('cgst_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='CGST Rate (%)')),
                ('sgst_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='SGST Rate (%)')),
                ('cgst_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='CGST Amount')),
                ('sgst_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='SGST Amount')),
                ('total_with_gst', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total with GST')),
                ('token_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Token Amount')),
                ('installation_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Installation Charges')),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Grand Total')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('converted', 'Converted to Quote')], default='new', max_length=20, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Admin Notes')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='products.productmasterv2', verbose_name='Selected Product')),
                ('quote_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to='products.quotesubmission', verbose_name='Related Quote')),
            ],
            options={
                'verbose_name': 'Product Form Submission',
                'verbose_name_plural': 'Product Form Submissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer_name', 'created_at'], name='products_pr_custome_0b1ade_idx'), models.Index(fields=['email', 'created_at'], name='products_pr_email_a02111_idx'), models.Index(fields=['mobile', 'created_at'], name='products_pr_mobile_5dd775_idx'), models.Index(fields=['status', 'created_at'], name='products_pr_status_2032a3_idx'), models.Index(fields=['product_id', 'created_at'], name='products_pr_product_19e52b_idx')],
            },
        ),
    ]
