# Generated by Django 5.2.4 on 2025-08-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_add_product_form_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttypemaster',
            name='app_password',
            field=models.CharField(blank=True, help_text='App password for the sender email account', max_length=255, null=True, verbose_name='App Password'),
        ),
        migrations.AddField(
            model_name='producttypemaster',
            name='sender_email',
            field=models.EmailField(blank=True, help_text='Email address for sending notifications for this product type', max_length=255, null=True, verbose_name='Sender Email'),
        ),
    ]
