# Generated by Django 5.2.4 on 2025-08-18 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_add_email_fields_to_productmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Name')),
                ('mobile', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='District')),
                ('pincode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Pincode')),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='GST Number')),
                ('additional_requirements', models.TextField(blank=True, null=True, verbose_name='Additional Requirements')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='new', max_length=20, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Admin Notes')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email Sent')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Email Sent At')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to='products.producttypemaster', verbose_name='Product Type')),
            ],
            options={
                'verbose_name': 'Quote Request',
                'verbose_name_plural': 'Quote Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer_name', 'created_at'], name='products_qu_custome_fba465_idx'), models.Index(fields=['email', 'created_at'], name='products_qu_email_00f3f3_idx'), models.Index(fields=['mobile', 'created_at'], name='products_qu_mobile_1b613e_idx'), models.Index(fields=['status', 'created_at'], name='products_qu_status_f94d84_idx'), models.Index(fields=['product_type', 'created_at'], name='products_qu_product_93608c_idx')],
            },
        ),
    ]
