# Generated by Django 5.2.4 on 2025-08-18 08:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_relax_customer_unique_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='DscPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_type', models.CharField(choices=[('class3', 'Class 3'), ('dgft', 'DGFT')], db_index=True, max_length=10)),
                ('user_type', models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization')], db_index=True, max_length=12)),
                ('cert_type', models.CharField(choices=[('signature', 'Signature'), ('encryption', 'Encryption'), ('both', 'Both')], db_index=True, max_length=12)),
                ('validity', models.CharField(choices=[('1y', '1 Year'), ('2y', '2 Years'), ('3y', '3 Years')], db_index=True, max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('outside_india_surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'DSC Price',
                'verbose_name_plural': 'DSC Prices',
                'unique_together': {('class_type', 'user_type', 'cert_type', 'validity')},
            },
        ),
    ]
