# Generated by Django 5.2.4 on 2025-08-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_remove_dscprice_price_dscprice_dsc_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
